// Package stock provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package stock

// CheckIfItemsInStockRequest defines model for CheckIfItemsInStockRequest.
type CheckIfItemsInStockRequest struct {
	Items *[]ItemWithQuantity `json:"items,omitempty"`
}

// CheckIfItemsInStockResponse defines model for CheckIfItemsInStockResponse.
type CheckIfItemsInStockResponse struct {
	InStock *bool   `json:"inStock,omitempty"`
	Items   *[]Item `json:"items,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// GetItemsRequest defines model for GetItemsRequest.
type GetItemsRequest struct {
	ItemIDs *[]string `json:"itemIDs,omitempty"`
}

// GetItemsResponse defines model for GetItemsResponse.
type GetItemsResponse struct {
	Items *[]Item `json:"items,omitempty"`
}

// Item defines model for Item.
type Item struct {
	Id       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	PriceID  *string `json:"priceID,omitempty"`
	Quantity *int32  `json:"quantity,omitempty"`
}

// ItemWithQuantity defines model for ItemWithQuantity.
type ItemWithQuantity struct {
	Id       *string `json:"id,omitempty"`
	Quantity *int32  `json:"quantity,omitempty"`
}

// PostItemsJSONRequestBody defines body for PostItems for application/json ContentType.
type PostItemsJSONRequestBody = GetItemsRequest

// PostItemsCheckJSONRequestBody defines body for PostItemsCheck for application/json ContentType.
type PostItemsCheckJSONRequestBody = CheckIfItemsInStockRequest
