// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: stockpb/stock.proto

package stockpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	orderpb "github.com/ecstasoy/gorder/common/genproto/orderpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreStockRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*orderpb.ItemWithQuantity `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockRequest) Reset() {
	*x = RestoreStockRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockRequest) ProtoMessage() {}

func (x *RestoreStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockRequest.ProtoReflect.Descriptor instead.
func (*RestoreStockRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreStockRequest) GetItems() []*orderpb.ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type RestoreStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreStockResponse) Reset() {
	*x = RestoreStockResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStockResponse) ProtoMessage() {}

func (x *RestoreStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStockResponse.ProtoReflect.Descriptor instead.
func (*RestoreStockResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{1}
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIDs       []string               `protobuf:"bytes,1,rep,name=ItemIDs,proto3" json:"ItemIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemsRequest) GetItemIDs() []string {
	if x != nil {
		return x.ItemIDs
	}
	return nil
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*orderpb.Item        `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemsResponse) GetItems() []*orderpb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckIfItemsInStockRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*orderpb.ItemWithQuantity `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIfItemsInStockRequest) Reset() {
	*x = CheckIfItemsInStockRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfItemsInStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfItemsInStockRequest) ProtoMessage() {}

func (x *CheckIfItemsInStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfItemsInStockRequest.ProtoReflect.Descriptor instead.
func (*CheckIfItemsInStockRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{4}
}

func (x *CheckIfItemsInStockRequest) GetItems() []*orderpb.ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type CheckIfItemsInStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InStock       bool                   `protobuf:"varint,1,opt,name=InStock,proto3" json:"InStock,omitempty"`
	Items         []*orderpb.Item        `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIfItemsInStockResponse) Reset() {
	*x = CheckIfItemsInStockResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfItemsInStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfItemsInStockResponse) ProtoMessage() {}

func (x *CheckIfItemsInStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfItemsInStockResponse.ProtoReflect.Descriptor instead.
func (*CheckIfItemsInStockResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{5}
}

func (x *CheckIfItemsInStockResponse) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *CheckIfItemsInStockResponse) GetItems() []*orderpb.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type WarmUpFlashStockRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*orderpb.ItemWithQuantity `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	TTLSeconds    int64                       `protobuf:"varint,2,opt,name=TTLSeconds,proto3" json:"TTLSeconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmUpFlashStockRequest) Reset() {
	*x = WarmUpFlashStockRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmUpFlashStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmUpFlashStockRequest) ProtoMessage() {}

func (x *WarmUpFlashStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmUpFlashStockRequest.ProtoReflect.Descriptor instead.
func (*WarmUpFlashStockRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{6}
}

func (x *WarmUpFlashStockRequest) GetItems() []*orderpb.ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *WarmUpFlashStockRequest) GetTTLSeconds() int64 {
	if x != nil {
		return x.TTLSeconds
	}
	return 0
}

type WarmUpFlashStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmUpFlashStockResponse) Reset() {
	*x = WarmUpFlashStockResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmUpFlashStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmUpFlashStockResponse) ProtoMessage() {}

func (x *WarmUpFlashStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmUpFlashStockResponse.ProtoReflect.Descriptor instead.
func (*WarmUpFlashStockResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{7}
}

type DeductStockRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*orderpb.ItemWithQuantity `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockRequest) Reset() {
	*x = DeductStockRequest{}
	mi := &file_stockpb_stock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockRequest) ProtoMessage() {}

func (x *DeductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockRequest.ProtoReflect.Descriptor instead.
func (*DeductStockRequest) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{8}
}

func (x *DeductStockRequest) GetItems() []*orderpb.ItemWithQuantity {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeductStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockResponse) Reset() {
	*x = DeductStockResponse{}
	mi := &file_stockpb_stock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockResponse) ProtoMessage() {}

func (x *DeductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stockpb_stock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockResponse.ProtoReflect.Descriptor instead.
func (*DeductStockResponse) Descriptor() ([]byte, []int) {
	return file_stockpb_stock_proto_rawDescGZIP(), []int{9}
}

var File_stockpb_stock_proto protoreflect.FileDescriptor

const file_stockpb_stock_proto_rawDesc = "" +
	"\n" +
	"\x13stockpb/stock.proto\x12\astockpb\x1a\x13orderpb/order.proto\"F\n" +
	"\x13RestoreStockRequest\x12/\n" +
	"\x05Items\x18\x01 \x03(\v2\x19.orderpb.ItemWithQuantityR\x05Items\"\x16\n" +
	"\x14RestoreStockResponse\"+\n" +
	"\x0fGetItemsRequest\x12\x18\n" +
	"\aItemIDs\x18\x01 \x03(\tR\aItemIDs\"7\n" +
	"\x10GetItemsResponse\x12#\n" +
	"\x05Items\x18\x01 \x03(\v2\r.orderpb.ItemR\x05Items\"M\n" +
	"\x1aCheckIfItemsInStockRequest\x12/\n" +
	"\x05Items\x18\x01 \x03(\v2\x19.orderpb.ItemWithQuantityR\x05Items\"\\\n" +
	"\x1bCheckIfItemsInStockResponse\x12\x18\n" +
	"\aInStock\x18\x01 \x01(\bR\aInStock\x12#\n" +
	"\x05Items\x18\x02 \x03(\v2\r.orderpb.ItemR\x05Items\"j\n" +
	"\x17WarmUpFlashStockRequest\x12/\n" +
	"\x05Items\x18\x01 \x03(\v2\x19.orderpb.ItemWithQuantityR\x05Items\x12\x1e\n" +
	"\n" +
	"TTLSeconds\x18\x02 \x01(\x03R\n" +
	"TTLSeconds\"\x1a\n" +
	"\x18WarmUpFlashStockResponse\"E\n" +
	"\x12DeductStockRequest\x12/\n" +
	"\x05Items\x18\x01 \x03(\v2\x19.orderpb.ItemWithQuantityR\x05Items\"\x15\n" +
	"\x13DeductStockResponse2\xa1\x03\n" +
	"\fStockService\x12?\n" +
	"\bGetItems\x12\x18.stockpb.GetItemsRequest\x1a\x19.stockpb.GetItemsResponse\x12`\n" +
	"\x13CheckIfItemsInStock\x12#.stockpb.CheckIfItemsInStockRequest\x1a$.stockpb.CheckIfItemsInStockResponse\x12K\n" +
	"\fRestoreStock\x12\x1c.stockpb.RestoreStockRequest\x1a\x1d.stockpb.RestoreStockResponse\x12W\n" +
	"\x10WarmUpFlashStock\x12 .stockpb.WarmUpFlashStockRequest\x1a!.stockpb.WarmUpFlashStockResponse\x12H\n" +
	"\vDeductStock\x12\x1b.stockpb.DeductStockRequest\x1a\x1c.stockpb.DeductStockResponseB4Z2github.com/ecstasoy/gorder/common/genproto/stockpbb\x06proto3"

var (
	file_stockpb_stock_proto_rawDescOnce sync.Once
	file_stockpb_stock_proto_rawDescData []byte
)

func file_stockpb_stock_proto_rawDescGZIP() []byte {
	file_stockpb_stock_proto_rawDescOnce.Do(func() {
		file_stockpb_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stockpb_stock_proto_rawDesc), len(file_stockpb_stock_proto_rawDesc)))
	})
	return file_stockpb_stock_proto_rawDescData
}

var file_stockpb_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_stockpb_stock_proto_goTypes = []any{
	(*RestoreStockRequest)(nil),         // 0: stockpb.RestoreStockRequest
	(*RestoreStockResponse)(nil),        // 1: stockpb.RestoreStockResponse
	(*GetItemsRequest)(nil),             // 2: stockpb.GetItemsRequest
	(*GetItemsResponse)(nil),            // 3: stockpb.GetItemsResponse
	(*CheckIfItemsInStockRequest)(nil),  // 4: stockpb.CheckIfItemsInStockRequest
	(*CheckIfItemsInStockResponse)(nil), // 5: stockpb.CheckIfItemsInStockResponse
	(*WarmUpFlashStockRequest)(nil),     // 6: stockpb.WarmUpFlashStockRequest
	(*WarmUpFlashStockResponse)(nil),    // 7: stockpb.WarmUpFlashStockResponse
	(*DeductStockRequest)(nil),          // 8: stockpb.DeductStockRequest
	(*DeductStockResponse)(nil),         // 9: stockpb.DeductStockResponse
	(*orderpb.ItemWithQuantity)(nil),    // 10: orderpb.ItemWithQuantity
	(*orderpb.Item)(nil),                // 11: orderpb.Item
}
var file_stockpb_stock_proto_depIdxs = []int32{
	10, // 0: stockpb.RestoreStockRequest.Items:type_name -> orderpb.ItemWithQuantity
	11, // 1: stockpb.GetItemsResponse.Items:type_name -> orderpb.Item
	10, // 2: stockpb.CheckIfItemsInStockRequest.Items:type_name -> orderpb.ItemWithQuantity
	11, // 3: stockpb.CheckIfItemsInStockResponse.Items:type_name -> orderpb.Item
	10, // 4: stockpb.WarmUpFlashStockRequest.Items:type_name -> orderpb.ItemWithQuantity
	10, // 5: stockpb.DeductStockRequest.Items:type_name -> orderpb.ItemWithQuantity
	2,  // 6: stockpb.StockService.GetItems:input_type -> stockpb.GetItemsRequest
	4,  // 7: stockpb.StockService.CheckIfItemsInStock:input_type -> stockpb.CheckIfItemsInStockRequest
	0,  // 8: stockpb.StockService.RestoreStock:input_type -> stockpb.RestoreStockRequest
	6,  // 9: stockpb.StockService.WarmUpFlashStock:input_type -> stockpb.WarmUpFlashStockRequest
	8,  // 10: stockpb.StockService.DeductStock:input_type -> stockpb.DeductStockRequest
	3,  // 11: stockpb.StockService.GetItems:output_type -> stockpb.GetItemsResponse
	5,  // 12: stockpb.StockService.CheckIfItemsInStock:output_type -> stockpb.CheckIfItemsInStockResponse
	1,  // 13: stockpb.StockService.RestoreStock:output_type -> stockpb.RestoreStockResponse
	7,  // 14: stockpb.StockService.WarmUpFlashStock:output_type -> stockpb.WarmUpFlashStockResponse
	9,  // 15: stockpb.StockService.DeductStock:output_type -> stockpb.DeductStockResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_stockpb_stock_proto_init() }
func file_stockpb_stock_proto_init() {
	if File_stockpb_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stockpb_stock_proto_rawDesc), len(file_stockpb_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stockpb_stock_proto_goTypes,
		DependencyIndexes: file_stockpb_stock_proto_depIdxs,
		MessageInfos:      file_stockpb_stock_proto_msgTypes,
	}.Build()
	File_stockpb_stock_proto = out.File
	file_stockpb_stock_proto_goTypes = nil
	file_stockpb_stock_proto_depIdxs = nil
}
