consul:
  addr: 127.0.0.1:8500

order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:9090
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:9091
  grpc-addr: 127.0.0.1:5003

payment:
    service-name: payment
    server-to-run: http
    http-addr: 127.0.0.1:9092
    grpc-addr: 127.0.0.1:5004
    processor: stripe                # mem = in-memory stub (压测); stripe = 真实 Stripe API (生产)

kitchen:
    service-name: kitchen

jaeger:
  url: "http://127.0.0.1:14268/api/traces"

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry-count: 5
  payment-timeout-ms: 30000

mongo:
  user: root
  password: password
  host: 127.0.0.1
  port: 27017
  db-name: "order"
  coll-name: "orders"

mysql:
  user: root
  password: root
  host: localhost
  port: 3307
  dbname: "gorder"

redis:
  local:
    ip: 127.0.0.1
    port: 6379
    pool_size: 100
    max_conn: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 100

fallback-grpc-addr: 127.0.0.1:5060
dial-grpc-timeout: 10s

stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"